#!/bin/bash

if [ -z "$APPDIR" ] ; then
   path="$(dirname "$(readlink -f "${THIS}")")"
   while [[ "$path" != "" && ! -e "$path/$1" ]]; do
       path=${path%/*}
   done
   APPDIR="$path"
fi

export PATH="${APPDIR}:${APPDIR}/usr/sbin:${PATH}"

cd "$APPDIR"

exec "$APPDIR/basic-chess-endgames-linux_x64" $@