#!/bin/bash

if [ -z "$APPDIR" ] ; then
   path="$(dirname "$(readlink -f "${THIS}")")"
   while [[ "$path" != "" && ! -e "$path/$1" ]]; do
       path=${path%/*}
   done
   APPDIR="$path"
fi

export GDK_BACKEND=x11
export PATH="${APPDIR}"
export LD_LIBRARY_PATH="${APPDIR}/usr/lib"
export XDG_DATA_DIRS="${APPDIR}"/usr/share/
export GSETTINGS_SCHEMA_DIR="${APPDIR}/usr/share/glib-2.0/schemas"

ldconfig

cd "$APPDIR"

exec "$APPDIR/basic-chess-endgames-linux_x64" $@