name: Build Linux AppImage
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
      - name: Install Neutralino
        run: npm i -g @neutralinojs/neu
      - name: Setup Neutralino backend
        run: neu update
      - name: Install dependencies
        run: cd frontend && npm i
      - name: Build frontend
        run: cd frontend && npm run build
      - name: Build backend
        run: npm run build:neu